package com.raj.schoolerp.entity;

public enum LeaveType {

	SICK_LEAVE,
    CASUAL_LEAVE,
    EMERGENCY_LEAVE,
    MEDICAL_LEAVE,
    HALF_DAY_LEAVE,
    FAMILY_FUNCTION_LEAVE,
    BEREAVEMENT_LEAVE,
    STUDY_LEAVE,
    MATERNITY_LEAVE,
    SPORTS_LEAVE,
    VACATION_LEAVE,
    SPECIAL_LEAVE
}
